config: !!python/object:edison.config.config.Config
  absolute_position_biased_input: false
  batch_size: 4
  beta_1: 0.9
  beta_2: 0.98
  device: cuda
  embedding_dim: 384
  epsilon: 1.0e-07
  gen_over_disc_ratio: 0.5
  gradient_accumulation_steps: 8
  gradient_clip_algorithm: norm
  gradient_clip_val: 1.0
  hidden_dim: 384
  hidden_dropout_prob: 0.1
  lambda_discriminator: 50.0
  layernorm_eps: 1.0e-07
  learning_rate: 0.0005
  load_pretrained_weights: true
  mask_lm_prob: 0.15
  max_preds_per_seq: null
  max_seq_len: 512
  normalize_relative_embedding: true
  num_head_dim: 64
  num_heads: 6
  num_hidden_layers: 12
  num_trainloader_workers: 16
  padding_idx: 0
  share_attention_weights: true
  share_embedding: gdes
  tokenizer_name: microsoft/deberta-v3-xsmall
  vocab_size: 128100
  weight_decay: 0.01
