config: !!python/object:edison.config.config.Config
  attn_head_dim: 64
  class_conditional: false
  class_unconditional_prob: 0.1
  d_model: 768
  dataset_name: roc
  dim_ae: 64
  dropout: 0.1
  gradient_accumulation_steps: 1
  gradient_clip_algorithm: norm
  gradient_clip_val: 1.0
  l2_normalize_latents: true
  latent_dim: 64
  learning_rate: 0.0001
  lm_dim: 768
  loss_type: l2
  max_seq_len: 64
  model_name: LD4LG
  num_classes: 0
  num_decoder_latents: 32
  num_dense_connections: 3
  num_encoder_latents: 32
  num_layers: 3
  num_samples: 1000
  objective: pred_v
  pretrained_ae_path: ''
  sampling_timesteps: 250
  scale: 1.0
  scale_shift: true
  self_condition: true
  train_batch_size: 8
  train_for: Diffusion
  train_prob_self_cond: 0.5
  transformer_decoder: true
  tx_depth: 12
  tx_dim: 768
