wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722148699.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.11.9
      5: 0.16.4
      6: 4.38.2
      8:
      - 1
      - 5
      13: darwin-arm64
