config: !!python/object:edison.config.config.Config
  d_model: 768
  dim_ae: 64
  gradient_accumulation_steps: 1
  gradient_clip_algorithm: norm
  gradient_clip_val: 1.0
  l2_normalize_latents: true
  learning_rate: 0.0001
  max_seq_len: 64
  model_name: LD4LG
  num_decoder_latents: 32
  num_encoder_latents: 32
  num_layers: 3
  train_batch_size: 256
  train_data: roc
  train_for: AE
  transformer_decoder: true
