config: !!python/object:deberta.config.Config
  absolute_position_biased_input: true
  batch_size: 32
  device: cuda
  embedding_dim: 1024
  gradient_clip_algorithm: norm
  gradient_clip_val: 1.0
  hidden_dim: 768
  hidden_dropout_prob: 0.1
  layernorm_eps: 1.0e-09
  learning_rate: 0.0001
  mask_lm_prob: 0.15
  max_preds_per_seq: null
  max_seq_len: 512
  num_head_dim: 64
  num_heads: 12
  num_hidden_layers: 12
  padding_idx: 0
  vocab_size: 128001
