wandb_version: 1

learning_rate:
  desc: null
  value: 0.002
architecture:
  desc: null
  value: test
dataset:
  desc: null
  value: test
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1721358048.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.4
      8:
      - 2
      - 5
      13: linux-x86_64
